---
- hosts: "{{ target }}"
  user: "{{ user }}" 
  tasks:
    - name: "Create ssh directory"
      file:
        path: "~/.ssh"
        state: directory
        mode: 0700
    - name: "Copy the public keys"
      copy:
        src: "authorized_keys"
        dest: "~/.ssh/authorized_keys"
        mode: 0600
