---
- hosts: "{{ target }}"
  remote_user: ec2-user
  become: true
  gather_facts: True
  vars:
    config_lvm: true                                        # must be set to true in order to execute any tasks in play
    create: true                                            # set to true if creating a new logical volume
    new_disk: '/dev/nvme1n1p1'                              # set to new disk being added to volume group
    new_mntp: '/var/lib/docker'                             # set to the desired mount point to be created and new logical volume to be mounted to
    create_vgname: 'docker-vg'                              # set to volume group name to create
    create_lvname: 'docker-pool'                            # set to logical volume name to create
    create_lvsize: '50%FREE'                                # set to logical volume size to create --- (10G) - would create new lvm with 10Gigabytes -- (512) - would create new lvm with 512m
    filesystem: 'xfs'                                       # set to filesystem type to format new logical volume with ( ext4, xfs, etc. )
    block_device_name: '/dev/nvme1n1'


  tasks:

    - name: "Install all the required binaries for lvm mgmt"
      yum:
        name: 'lvm*'
        state: present


    - parted:
        device: '/dev/nvme1n1'
        number: 1
        flags: [ lvm ]
        state: present
        part_start: 1MiB


    - name: "Creating new LVM volume group"
      lvg: vg={{ create_vgname }} pvs={{ new_disk }} state=present
      when: create and config_lvm


    - name: "Creating new LVM logical volume"
      lvol: vg={{ create_vgname }} lv={{ create_lvname }} size={{ create_lvsize }}
      when: create and config_lvm


    - name: "Creating new filesystem on new LVM logical volume"
      filesystem: fstype={{ filesystem }} dev=/dev/{{ create_vgname }}/{{ create_lvname }}
      when: create and config_lvm


    - name: "Mounting new filesystem"
      mount: name={{ new_mntp }} src=/dev/{{ create_vgname }}/{{ create_lvname }} fstype={{ filesystem }} state=mounted
      when: create and config_lvm
