---
- hosts: "{{ target }}"
  remote_user: ec2-user
  become: true
  gather_facts: True

  tasks:

    - lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=permissive'

    - name: "Auto relabel.."
      command: touch /.autorelabel
      register: task_result

    - name: Reboot immediately if there was a change.
      shell: "sleep 10 && reboot"
      async: 1
      poll: 0
      when: task_result is changed

    - name: Wait for the reboot to complete if there was a change.
      wait_for_connection:
	connect_timeout: 20
	sleep: 5
	delay: 5
	timeout: 300
      when: task_result is changed


    - lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=enforcing'

    - name: "Auto relabel.."
      command: touch /.autorelabel
      register: task_result

    - name: Reboot immediately if there was a change.
      shell: "sleep 10 && reboot"
      async: 1
      poll: 0
      when: task_result is changed

    - name: Wait for the reboot to complete if there was a change.
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300
      when: task_result is changed
