- hosts: localhost
  vars:
    aws_profile: "{{ lookup('ansible.builtin.env', 'AWS_PROFILE', default='XXXXX') }}"    
    aws_region: "{{ lookup('ansible.builtin.env', 'AWS_REGION', default='ap-southeast-2') }}"
    dbenv: "{{ lookup('ansible.builtin.env', 'ENV', default='YYYY') }}"

    sm_versions: ['AWSCURRENT', 'AWSPREVIOUS', 'AWSPENDING']
    users: ['user1', 'user2', 'user3', 'user4']

    on_denied: 'warn'
    on_missing: 'warn'
    nested: true

  gather_facts: no

  tasks:

  - name: Retrieve Password
    vars:
    ansible.builtin.debug:
      msg: "{{ lookup('amazon.aws.aws_secret', 
                '/platform/application/rds/app-db/{{dbenv}}-{{cidr_sm_ver_product.0}}.username', 
                nested=nested, 
                on_missing=on_missing, 
                on_denied=on_denied, 
                version_stage=cidr_sm_ver_product.1, 
                region=aws_region)
              ,
              lookup('amazon.aws.aws_secret', '/platform/application/rds/app-db/{{dbenv}}-{{cidr_sm_ver_product.0}}.password', 
                nested=nested, 
                on_missing=on_missing, 
                on_denied=on_denied, 
                version_stage=cidr_sm_ver_product.1, 
                region=aws_region) 
            }}"
    loop: "{{ users | product(sm_versions) | list }}"
    loop_control:
      loop_var: cidr_sm_ver_product
