---
- hosts: "{{ target }}"
  gather_facts: 'no'

  # SOP documented here: https://access.redhat.com/solutions/24845
  # Insert Ansible Execution Command

  tasks:

    - name: "Current OS version.."
      command: uname -a

    - name: Preserve environment variables
      lineinfile:
        path: /etc/sudoers
        regexp: '^Defaults    env_reset'
        line: 'Defaults    !env_reset'

    - name: "Copy the hip user crontab"
      copy:
        src: "hip-user"
        dest: "/var/spool/cron/hip-user"
        mode: 0600

    - name: "Copy selinux permissive"
      copy:
        src: "selinux.permissive"
        dest: "/etc/selinux/config"
        mode: 0600

    - name: "Auto relabel.."
      command: touch /.autorelabel

    - name: "Reboot system"
      shell: sleep 2 && shutdown -r now "To set selinux to enforcing"
      async: 1
      poll: 0
      ignore_errors: true

    - name: "Waiting for server to come back"
      local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=120
      sudo: false


    - name: "Check selinux status.."
      command: getenforce


    - name: "Copy selinux enforcing"
      copy:
        src: "selinux.enforcing"
        dest: "/etc/selinux/config"
        mode: 0600


    - name: "Auto relabel.."
      command: touch /.autorelabel

    - name: "Reboot system"
      shell: sleep 2 && shutdown -r now "To set selinux to enforcing"
      async: 1
      poll: 0
      ignore_errors: true

    - name: "Waiting for server to come back"
      local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=120
      sudo: false

    - name: "Check selinux status.."
      command: getenforce
